version: '3.8'

services:
  db:
    image: timescale/timescaledb-ha:pg16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: homework # creates db so no need in schema, rm this
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
