services:
  db:
    image: timescale/timescaledb-ha:pg16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/cpu_usage.sql:/docker-entrypoint-initdb.d/script.sql
      - ./db/import-data.sh:/docker-entrypoint-initdb.d/setup.sh
      - ./db/cpu_usage.csv:/docker-entrypoint-initdb.d/cpu_usage.csv
